spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 1234
  thymeleaf:
    cache: false


server:
<<<<<<< HEAD
  port: 8090
=======
  port: 7000
>>>>>>> 559b4f2 (Initial commit)



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.project.solutionpackage.model
